spring:
  application:
    name: car4r
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/, classpath:/public/

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: info

jwt: # ms
  expiration:
    accessToken: 86400000 # 1 day
    refreshToken: 2592000000 # 30 days
    verifyToken: 300000 # 3 minutes


payment:
  vnPay:
    url: ${PAY_URL}
    tmnCode: ${TMN_CODE}
    secrectKey: ${SECRET_KEY}
    version: ${VERSION}
    command: ${COMANND}
    orderType: ${ORDER_TYPE}
