spring:
  # config database
  datasource: #database
    url: jdbc:mysql://localhost:3306/AppFilm
    username: root
    password: Khongco2004@
    driver-class-name: com.mysql.cj.jdbc.Driver

  # config jpa
  jpa: #jpa
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: none
    show_sql: true

  # config port
  server:
    port: 8080

  # config log
  logging:
    level:
      org:
        springframework:
          web: info
