spring:
  application:
    name: car4r
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        web: info

  # config mail
mail:
  host: smtp.gmail.com
  port: 587
  username: hieuhoctap2004@gmail.com
  password: skgb robb lkva upam
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true

jwt: # ms
  expiration:
    accessToken: 86400000 # 1 day
    refreshToken: 2592000000 # 30 days
    verifyToken: 300000 # 3 minutes


payment:
  vnPay:
    url: ${PAY_URL}
    tmnCode: ${TMN_CODE}
    secrectKey: ${SECRET_KEY}
    version: ${VERSION}
    command: ${COMANND}
    orderType: ${ORDER_TYPE}